### ISSUE TITLE
Increase readability of URLs

### ISSUE THREAD

**Issue by taskmaker1** [uccser/dthm4kaiako#204]
A URL like `https://dthm4kaiako.ac.nz/dtta/page/1/` should redirect a version where a slug is present
`https://dthm4kaiako.ac.nz/dtta/page/1/title-goes-here` for readability of URLs when pasted.

Also the metadata title of each page should be set should URL previewers show the correct title.

**Comment by JackMorganNZ** [comment]
Will do some research to see how easy this is to implement.
