### ISSUE TITLE
news page, not found

### ISSUE THREAD

**Issue by taskmaker1** [uccser/dthm4kaiako#259]
added in a new news page and it is returning an error, page not found.

https://www.dthm4kaiako.ac.nz/dtta/news/7/technology-online-webinar-kia-takatu-a-matihiko/

I have added in a new news resource, into this as well, kia takatu, no image though, just the web link?

**Comment by JackMorganNZ** [comment]
There is still an issue with the date/time logic regarding timezones and when to display content.

I have set the news date to be one day earlier for the moment so the news article is shown, but will look into the backend and either fix the bug, or remove the dynamic datetime filtering, and switch to a simple published/unpublished option.

**Comment by JackMorganNZ** [comment]
Fixed in 0.9.4
