### ISSUE TITLE
Overseas links

### ISSUE THREAD

**Issue by taskmaker1** [uccser/dthm4kaiako#274]
Do you think it might be helpful to have an ‘overseas resources’ section on dthm4k pointing to the big ones - CAS, CSTA, Aussy hub, code.org. ... to save teachers rediscovering them? (With a warning that they aren’t directly designed for NZ, but have a lot of useful free material for those interests in exploring).

**Comment by JackMorganNZ** [comment]
This was discussed in workplace, and decision was made to treat all resources individually. If a good, for example, CSTA resource is discovered, it can be added to the resource hub as one item, with instructions to match it to the DTHM curricula. The resource hubs themselves are too large to describe with a set of tags and a rating.

We can list other resource hubs on an about page to point users to other resource locations.
