### ISSUE TITLE
Achievement Objective card generator

### ISSUE THREAD

**Issue by taskmaker1** [uccser/dthm4kaiako#294]
Using the Learning Area, to generate card colour, WIth the achievement Objective randomly generated on the back, based upon curriculum levels that the user selects. Generate a random 52 cards for people to use to find authentic contexts.

Develop this on the existing work done by taskmaker1
http://stbedesdtg.com/nzc/

**Comment by JackMorganNZ** [comment]
After planning discussion with @taskmaker1 and @tah942, the following tasks are to be done:

- [ ] Load all achievement outcomes.
- [ ] Create card design with CSS.
- [ ] Create webpage template for unbranded (or minimal branded) resources.
- [ ] Create Django application for authentic context prompter (name TBC).
- [ ] Create webpage with random card.
- [ ] Create form for selecting type of card.
- [ ] Add logic for determining card set.
- [ ] Use Weasyprint for generate PDF of cards.
- [ ] Create static file of all cards (to avoid rendering on request).
- [ ] Allow user to download a set of random 52 cards for selected year levels:
  - [ ] Test using Weasyprint to generate on request (likely to lock server).
  - [ ] Test using queue to render on request (longer development time).
