### ISSUE TITLE
issue in events home page

### ISSUE THREAD

**Issue by taskmaker1** [uccser/dthm4kaiako#325]
When an event is over two days, formatting needs to be fixed, even though it shows, correctly if copied. It is too bunched up on the page
17 to 18 April, 2019
![Screen Shot 2019-03-19 at 9 39 39 PM](https://user-images.githubusercontent.com/46875857/54591734-bc36d680-4a8f-11e9-97fa-5974bcb6e4c9.png)

**Comment by JackMorganNZ** [comment]
I haven't been able to replicate this bug, but I will restructure the way space is allocated to the name and dates. In the example above, the location should be removed from the title too to reduce the space taken.
