### ISSUE TITLE
Missing bindings for Django Storages

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/dthm4kaiako#363]
# Problem

After releasing [0.14.0](https://github.com/uccser/dthm4kaiako/pull/360), most webpage hits were returning a 500 error, and the following error log was sent to us:

```
Internal Server Error: /

ImproperlyConfigured at /
Could not load Google Cloud Storage bindings.
See https://github.com/GoogleCloudPlatform/gcloud-python

File "/docker_venv/lib/python3.6/site-packages/storages/backends/gcloud.py" in <module>
  22.     raise ImproperlyConfigured("Could not load Google Cloud Storage bindings.\n"
```

This was an odd error to see as nothing had changed related to the configuration of our storage settings, and nothing had changed with the storage dependencies.

# Investigation

The line raising the issue within the Django Storages package was to do with the [following lines](https://github.com/jschneier/django-storages/blob/master/storages/backends/gcloud.py#L17-L23):

```python
try:
    from google.cloud.storage.client import Client
    from google.cloud.storage.blob import Blob
    from google.cloud.exceptions import NotFound
except ImportError:
    raise ImproperlyConfigured("Could not load Google Cloud Storage bindings.\n"
                               "See https://github.com/GoogleCloudPlatform/gcloud-python")
```

I SSHed into one of the running instances and started up a Python3 shell and tried each of one these imports. The first two failed with the same error:

```
Traceback (most recent call last):
  File "/docker_venv/lib/python3.6/site-packages/google/resumable_media/requests/__init__.py", line 665, in <module>
    pkg_resources.require('requests >= 2.18.0')
  File "/docker_venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/docker_venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25.2 (/docker_venv/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.21.1'), {'requests'})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/docker_venv/lib/python3.6/site-packages/google/cloud/storage/__init__.py", line 39, in <module>
    from google.cloud.storage.blob import Blob
  File "/docker_venv/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 44, in <module>
    from google.resumable_media.requests import ChunkedDownload
  File "/docker_venv/lib/python3.6/site-packages/google/resumable_media/requests/__init__.py", line 673, in <module>
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
ImportError: ``requests >= 2.18.0`` is required by the ``google.resumable_media.requests`` subpackage.
It can be installed via
    pip install google-resumable-media[requests].
```

Installing `google-resumable-media[requests]` as the error log suggests resulted in the following message:

```
Requirement already satisfied: google-resumable-media[requests] in /docker_venv/lib/python3.6/site-packages (0.3.2)
Requirement already satisfied: six in /docker_venv/lib/python3.6/site-packages (from google-resumable-media[requests]) (1.12.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0; extra == "requests" in /docker_venv/lib/python3.6/site-packages (from google-resumable-media[requests]) (2.21.0)
Requirement already satisfied: certifi>=2017.4.17 in /docker_venv/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0; extra == "requests"->google-resumable-media[requests]) (2019.3.9)
Collecting urllib3<1.25,>=1.21.1 (from requests<3.0.0dev,>=2.18.0; extra == "requests"->google-resumable-media[requests])
  Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 14.7MB/s 
Requirement already satisfied: idna<2.9,>=2.5 in /docker_venv/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0; extra == "requests"->google-resumable-media[requests]) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /docker_venv/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0; extra == "requests"->google-resumable-media[requests]) (3.0.4)
Installing collected packages: urllib3
  Found existing installation: urllib3 1.25.2
    Uninstalling urllib3-1.25.2:
      Successfully uninstalled urllib3-1.25.2
Successfully installed urllib3-1.24.3
```

This is the first time a dependency has changed, the package `urllib3` downgraded from `1.25.2` to `1.24.3`. Adding `urllib3==1.24.3` as a dependency to the repository's requirements file fixed the import issue and the website was operation again.

Strangely the issue was not occuring on the dev website.

# Questions

Q: What caused the dependency issue? 
A: ?

Q: What caused the issue to occur at this time?
A (possible - to investigate): Creating new docker images for the release since the dependency change occured caused the problem. The problem could have been there any time since the last release, but wouldn't have been exposed until the next release. 

Q: Why did this not occur on the dev website?
A: ?

**Comment by eAlasdair** [comment]
As asked I did some research, though server-side issues are not my forte especially with no knowledge of the server.

- urllib3 1.25.2 was released to the [Master branch](https://github.com/urllib3/urllib3/tree/master) 17 days ago, or approximately May 1st.
- urllib3 1.24.3 was released to the [**1.24-series branch**](https://github.com/urllib3/urllib3/tree/1.24-series) 14 days ago, or approximately May 4th. (this branch was [created in early November](https://github.com/urllib3/urllib3/network))
- This would imply there are at least two branches being actively developed in the same repo.
- In the first two levels of [dependencies](https://github.com/uccser/dthm4kaiako/network/dependencies), urllib3 is required as follows:
  - elasticsearch-py: Requires:
    - urllib3 `>= 1.21.1`
    - kennethreitz/requests: Requires:
      - urllib3 `< 1.25.0 || > 1.25.0, < 1.25.1 || > 1.25.1, < 1.26, >= 1.21.1` (note 1.25.2 is the only 1.25.x version permitted currently)
- There could be others but I didn't look at further levels of dependencies

Both releases happened between 1.3.3 (March 22) and 1.4.0 (May 14).

### Other notes:
> Adding urllib3==1.24.3 as a dependency to the repository's requirements file fixed the import issue and the website was operation again.

- This was made to the `hotfix/0.14.3` branch but `master` and the website in general is (at the time of writing) running successfully on 0.14.2 without the change.

### So:

> Q: What caused the dependency issue?

My theory:
`kennethreitz/requests` using urllib3 was using a 1.24.x version. At the time there was no version in 1.25.x that it supported. As such `elasticsearch-py` was having difficulties between the 1.25.2 release of urllib and a few hours ago when `requests` was updated to support it (see pull/5092 of [https://github.com/kennethreitz/requests](https://github.com/kennethreitz/requests)).
This would also explain why the current site is working fine

> Q: What caused the issue to occur at this time?

My theory:
It was unfortunate luck to release 0.14.0 in this period and if it were done today everything would've been fine

> Q: Why did this not occur on the dev website?

Maybe Docker didn't need to rebuild it until it was released to the live version? I don't know the dev site and I don't have access to the server so I have no idea

**Comment by JackMorganNZ** [comment]
> ### Other notes:
> > Adding urllib3==1.24.3 as a dependency to the repository's requirements file fixed the import issue and the website was operation again.
> 
> * This was made to the `hotfix/0.14.3` branch but `master` and the website in general is (at the time of writing) running successfully on 0.14.2 without the change.

It would be hard to spot, but on this branch I was deploying the app to Google App Engine to check the fix would work (because it wasn't occuring on the dev website). I will soon make an official release with this fix.

**Comment by JackMorganNZ** [comment]
@eAlasdair Thanks for that research, great find (I didn't come across that shared dependency with `elasticsearch-py` during my initial search). Seems like bad luck timing!

Will definitely need to do some thinking about why it didn't trigger on the dev website. Possibly because no tests actually use storage on GCP? But then again that would stop it from importing it... :thinking:

**Comment by eAlasdair** [comment]
No worries, regarding this:

> > ### Other notes:
> > > Adding urllib3==1.24.3 as a dependency to the repository's requirements file fixed the import issue and the website was operation again.
> > 
> > 
> > 
> > * This was made to the `hotfix/0.14.3` branch but `master` and the website in general is (at the time of writing) running successfully on 0.14.2 without the change.
> 
> It would be hard to spot, but on this branch I was deploying the app to Google App Engine to check the fix would work (because it wasn't occuring on the dev website). I will soon make an official release with this fix.

I suspect that's not needed anymore, I think the current version just needs to be rebuilt

**Comment by JackMorganNZ** [comment]
You're correct, tested the old version and all is working fine. Will close this issue.
